services:
  mongo:
    image: mongo
    container_name: main-service-mongo
    profiles: ["api"]
    ports:
      - "27017:27017"

  mongo-dataset:
    image: mongo
    container_name: dataset-mongo
    profiles: ["dataset"]
    ports:
      - "27018:27017"

  ml-weather:
    build: ./services/ML_service
    container_name: ml-weather-service
    profiles: ["api"]
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - WEATHER_ARTIFACT_DIR=/app/artifacts
      - OMP_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - BLIS_NUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
    volumes:
      - ./services/ML_service/artifacts:/app/artifacts:ro
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  weather-service:
    build: ./services/weather_service
    container_name: weather-service
    profiles: ["api"]
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - APP_NAME=weather-service
      - APP_VERSION=1.0.0
      - REQUEST_TIMEOUT_SECONDS=20
      - MACHINE_BASE_URL=http://ml-weather:8000
      - MACHINE_PREDICT_PATH=/predict-weather-physics
      - OPENMETEO_ARCHIVE_URL=https://archive-api.open-meteo.com/v1/archive
    depends_on:
      - ml-weather
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080

  algorithm:
    build: ./services/algorithm_service
    container_name: algorithm-service
    profiles: ["api"]
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SERVICE_MODE=api
      - WEATHER_SERVICE_URL=http://weather-service:8080
      - WEATHER_SERVICE_PATH=/weather
      - WEATHER_PROVIDER_TIMEOUT_S=5.0
    depends_on:
      - weather-service
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  algorithm-dataset:
    build: ./services/algorithm_service
    container_name: algorithm-dataset
    profiles: ["dataset"]
    environment:
      - SERVICE_MODE=dataset
      - ERA5_DIR=/data/era5
      - ERA5_MAX_CACHED_HOURS=2
      - N_SAMPLES=200000
      - OUTPUT_DATASET=/data/dataset_200k.jsonl
      - GEN_THREADS=2
      - GEN_MAX_IN_FLIGHT=2
      - GEN_SEED=42
      - SKIP_ERA5_DAYS=19
    volumes:
      - ./data/era5:/data/era5
      - ./data:/data
    command: python -m modules.atmosphere.generate_dataset_fast

  main:
    build: ./services/main-service
    ports:
      - "3000:3000"
    profiles: ["api"]
    env_file:
      - ./services/main-service/.env
    depends_on:
      - mongo
      - algorithm

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    profiles: ["api"]
    depends_on:
      - main
