services:
  mongo:
    image: mongo
    container_name: main-service-mongo
    profiles: ["api"]
    ports:
      - "27017:27017"

  mongo-dataset:
    image: mongo
    container_name: dataset-mongo
    profiles: ["dataset"]
    ports:
      - "27018:27017"

  algorithm:
    build: ./services/algorithm_service
    container_name: algorithm-service
    profiles: ["api"]
    ports:
      - "8000:8000"
    environment:
      - SERVICE_MODE=api
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  algorithm-dataset:
    build: ./services/algorithm_service
    container_name: algorithm-dataset
    profiles: ["dataset"]
    ports:
      - "8001:8000"
    environment:
      - SERVICE_MODE=dataset
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 14

  main:
    build: ./services/main-service
    ports:
      - "3000:3000"
    profiles: ["api"]
    env_file:
      - ./services/main-service/.env
    depends_on:
      - mongo
      - algorithm

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    profiles: ["api"]
    depends_on:
      - main
