"""
Ground impact detection via linear zero-crossing interpolation.

This module detects the first ground-impact event in a discrete
trajectory generated by a numerical integrator. Impact is treated
as a zero-crossing event of the altitude state variable.

When altitude changes sign between two consecutive samples
(z > z_ground → z ≤ z_ground), the impact instant is approximated
by linear interpolation in time, and the full 3DOF state is
interpolated accordingly.

Method
------
Given two consecutive samples (k-1, k) such that:

    z_{k-1} > z_ground  and  z_k ≤ z_ground

the interpolation fraction t is computed as:

    t = (z_{k-1} - z_ground) / (z_{k-1} - z_k)

For the common case z_ground = 0:

    t = z_{k-1} / (z_{k-1} - z_k)

Each component of the state vector is then linearly interpolated
using the same fraction t.

Assumptions
-----------
• Ground altitude is constant.
• Altitude is locally monotonic near impact.
• Sampling resolution is sufficient for linear interpolation
  to approximate the true impact time.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from modules.state.state import State3DOF


# ============================================================
# Numerical constants
# ============================================================

GROUND_ALTITUDE_M: float = 0.0
"""Reference ground altitude for impact detection."""

INTERPOLATION_EPSILON: float = 1e-12
"""Tolerance to prevent division-by-zero in interpolation."""

INTERPOLATION_MIN_FRACTION: float = 0.0
INTERPOLATION_MAX_FRACTION: float = 1.0
"""Valid bounds for interpolation fraction."""

MIN_TRAJECTORY_LENGTH: int = 2
"""Minimum number of samples required for event detection."""


# ============================================================
# Impact result container
# ============================================================

@dataclass(frozen=True)
class ImpactResult:
    """
    Result of ground-impact event detection.

    Attributes
    ----------
    state_at_impact : State3DOF
        Interpolated state at impact (altitude forced to ground level)
    index_before : int
        Index of the last sample above ground
    index_after : int
        Index of the first sample at/below ground
    interpolation_fraction : float
        Linear interpolation fraction between the two samples
    """

    state_at_impact: State3DOF
    index_before: int
    index_after: int
    interpolation_fraction: float


# ============================================================
# Interpolation utilities
# ============================================================

def linear_interpolate(
    start_value: float,
    end_value: float,
    fraction: float,
) -> float:
    """
    Linear interpolation between two scalar values.
    """

    return start_value + (end_value - start_value) * fraction


def interpolate_state(
    start_state: State3DOF,
    end_state: State3DOF,
    fraction: float,
) -> State3DOF:
    """
    Linearly interpolate between two State3DOF states.
    """

    return State3DOF(
        x=linear_interpolate(start_state.x, end_state.x, fraction),
        z=linear_interpolate(start_state.z, end_state.z, fraction),
        vx=linear_interpolate(start_state.vx, end_state.vx, fraction),
        vz=linear_interpolate(start_state.vz, end_state.vz, fraction),
        theta=linear_interpolate(start_state.theta, end_state.theta, fraction),
        q=linear_interpolate(start_state.q, end_state.q, fraction),
    )


# ============================================================
# Impact detection
# ============================================================

def compute_impact_from_trajectory(
    trajectory: List[State3DOF],
) -> Optional[ImpactResult]:
    """
    Detect the first ground-crossing event in a trajectory.

    Returns an interpolated impact state if a crossing is detected.
    """

    if len(trajectory) < MIN_TRAJECTORY_LENGTH:
        return None

    if trajectory[0].z <= GROUND_ALTITUDE_M:
        return None

    for index in range(1, len(trajectory)):

        previous_state = trajectory[index - 1]
        current_state = trajectory[index]

        z_prev = previous_state.z
        z_curr = current_state.z

        crossing_detected = (
            z_prev > GROUND_ALTITUDE_M >= z_curr
        )

        if not crossing_detected:
            continue

        altitude_delta = z_prev - z_curr

        if abs(altitude_delta) < INTERPOLATION_EPSILON:
            fraction = INTERPOLATION_MIN_FRACTION
        else:
            fraction = z_prev / altitude_delta

        fraction = max(
            INTERPOLATION_MIN_FRACTION,
            min(INTERPOLATION_MAX_FRACTION, fraction),
        )

        interpolated_state = interpolate_state(
            previous_state,
            current_state,
            fraction,
        )

        impact_state = State3DOF(
            x=interpolated_state.x,
            z=GROUND_ALTITUDE_M,
            vx=interpolated_state.vx,
            vz=interpolated_state.vz,
            theta=interpolated_state.theta,
            q=interpolated_state.q,
        )

        return ImpactResult(
            state_at_impact=impact_state,
            index_before=index - 1,
            index_after=index,
            interpolation_fraction=fraction,
        )

    return None
